spring:
  datasource:
    url: jdbc:oracle:thin:@${SSERVER:192.168.1.10}:${SPORT:1521}/${SDB:FREEPDB1}
    username: ${DB_USERNAME:MDEIUSER}
    password: ${DB_PASSWORD:einvoice@123}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

program:
#  task-type: '${TASK_TYPE:PUBLISH}'
  task-type: '${TASK_TYPE:GENERATE}'
#types :  PUBLISH, GENERATE

xml-gen:
  invoice-id: 1833496250
  is-staging: '${XML_GEN_IS_STAGING:false}'

qr:
  signing:
    private:
      key: '${PRIVATE_KEY_ENCODED_BASE64:TUhRQ0FRRUVJRmFjOVIwWGZaaUMvQ0JnU3ZZU3hQcjFGdHREL1diNlJqMmhOY0p0emJ2MW9BY0dCU3VCQkFBS29VUURRZ0FFSUgwdVlGOXNxN1lLOGNKRlg0M0QvRTBHdEgvMi9WcmhJWnFJSWRrd1k4d3Z5ckErOXp5NXZjTmdqT3FpY3RlbTgyMWFVM21MWkE5QkQvdGNML3hSV0E9PQ==}'
  generation:
    service:
      #      id: '${QR_SERVICE_ID:1ba47f64-f34f-48eb-b3b4-cb1208d20105}'
      id: '${QR_SERVICE_ID:}'

signing:
  enabled: '${SIGNING_ENABLED:true}'
  include-comment: '${SIGNING_INCLUDE_SAMPLE_COMMENT:true}'
  private:
    key: '${SIGNING_PRIVATE_KEY:MHQCAQEEIHctzuxMs3hyuwR59xcIlomxEZ0qZ+yNFG6qhdsUMxEAoAcGBSuBBAAKoUQDQgAEgrGgqkDGfZ3D5Ov4FjZNL+fWHeWwQ/qGeFufHTCPPeSF8FsdUxIMZUr5nevSg4u+TEcIjHJQOpTa9wDZJ0gcfw==}'
  certificate: '${SIGNING_CERTIFICATE:MIICbjCCAhSgAwIBAgIUU8D7Ftj3UMnviXGgbsFcIBghUYwwCgYIKoZIzj0EAwIwgY0xCzAJBgNVBAYTAkpPMQ4wDAYDVQQIDAVBbW1hbjEOMAwGA1UEBwwFQW1tYW4xDTALBgNVBAoMBElTVEQxDTALBgNVBAsMBEVUQVgxGTAXBgNVBAMMEGV0YXguaXN0ZC5nb3Yuam8xJTAjBgkqhkiG9w0BCQEWFmFkbWluQGV0YXguaXN0ZC5nb3Yuam8wHhcNMjIwOTEzMTIwNzI4WhcNMjMwOTEzMTIwNzI4WjCBjTELMAkGA1UEBhMCSk8xDjAMBgNVBAgMBUFtbWFuMQ4wDAYDVQQHDAVBbW1hbjENMAsGA1UECgwESVNURDENMAsGA1UECwwERVRBWDEZMBcGA1UEAwwQZXRheC5pc3RkLmdvdi5qbzElMCMGCSqGSIb3DQEJARYWYWRtaW5AZXRheC5pc3RkLmdvdi5qbzBWMBAGByqGSM49AgEGBSuBBAAKA0IABIKxoKpAxn2dw+Tr+BY2TS/n1h3lsEP6hnhbnx0wjz3khfBbHVMSDGVK+Z3r0oOLvkxHCIxyUDqU2vcA2SdIHH+jUzBRMB0GA1UdDgQWBBR84PMuVc1aJGzD0tbw2e/L3tfdFzAfBgNVHSMEGDAWgBR84PMuVc1aJGzD0tbw2e/L3tfdFzAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0gAMEUCIQDuAysSYRdzcoWo31lyzTYGOGEk0h/ElzlGF2qd3M5cHAIgX/awycpO2F2GKY5qBcgwOlncOooEM1GhO9tkA/GqOAQ=}'

# todo remove later on
publisher:
  path: '${PUBLISHER_PATH:C:\Users\USER\OneDrive - readytech\Desktop\I&R}'
  taxpayer: '${TAXPAYER:777777773}'


minio:
  endpoint: '${MINIO_ENDPOINT:http://localhost:9000}'
  access-key: '${MINIO_ACCESS_KEY:minioadmin}'
  secret-key: '${MINIO_SECRET_KEY:minioadmin123}'
  bucket-name: '${MINIO_BUCKET_NAME:einvoice-xml}'
